# GET receber algo
# POST criar algo
# PUT alterar algo
# PATCH alterar parte de algo
# DELETE deletar algo

###
GET http://localhost:3333/user

###
GET http://localhost:3333/user?filter=Hu

###
POST http://localhost:3333/user HTTP/1.1
Content-Type: application/json

{
    "email": "hugo@gmail.com",
    "senha": 12345678,
    "nome": "Hugo",
    "idade": 20,
    "altura": 1.70,
    "peso": 65.0
}

###
POST http://localhost:3333/user HTTP/1.1
Content-Type: application/json

{
    "email": "hidel@gmail.com",
    "senha": 12345678,
    "nome": "Hidel",
    "idade": 20,
    "altura": 1.70,
    "peso": 65.0
}

###
POST http://localhost:3333/user HTTP/1.1
Content-Type: application/json

{
    "email": "pedro@gmail.com",
    "senha": 12345678,
    "nome": "Pedro",
    "idade": 21,
    "altura": 1.70,
    "peso": 55
}

###
DELETE http://localhost:3333/user/08158973-c25d-4afd-aadc-b4b52cb2a875 HTTP/1.1

###
PUT http://localhost:3333/user/873057b0-475e-4061-b5ad-0e2ab03dda16 HTTP/1.1
Content-Type: application/json

{
    "idade": 21,
    "altura": 1.70,
    "peso": 65.0
}