# GET receber algo
# POST criar algo
# PUT alterar algo
# PATCH alterar parte de algo
# DELETE deletar algo

###
GET http://localhost:3333/user

###
GET http://localhost:3333/user?filter=Hu

###
POST http://localhost:3333/user HTTP/1.1
Content-Type: application/json

{
    "nome": "Hugo",
    "idade": 20
}

###
POST http://localhost:3333/user HTTP/1.1
Content-Type: application/json

{
    "nome": "Hidel",
    "idade": 20
}

###
PUT http://localhost:3333/user/873057b0-475e-4061-b5ad-0e2ab03dda16 HTTP/1.1
Content-Type: application/json

{
    "idade": 21,
    "altura": 1.70,
    "peso": 65.0
}

###
DELETE http://localhost:3333/user/04d487bf-e48e-48fc-a2de-16b60aab22ce HTTP/1.1